version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - run: echo "Build it's done! tests are passing"
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "94:97:76:ba:3f:5b:2f:3f:6b:90:4d:67:f9:02:d2:09"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST ./deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
